### ISSUE TITLE
Add test for IO test assertion items

### ISSUE THREAD

**Issue by timonSchenzel** [timonSchenzel/counsel#7]
Add test for IO test assertion items, like version. Mock the version in some way?

**Comment by timonSchenzel** [comment]
IO Test example:

```yaml
test:
  Dot reporter output
perform:
  src/counsel.js --config io-tests/configs/dot-reporter-success-reporting-test.js --is-io-test
expect: |
  Counsel {{version}}

  ...............           15 / 15 (100%)

  Time: {{executionTimeFormatted}}
  15 passed, 15 tests
assertions:
  status: 0
  version: 0.0.1 <----- need to test this
```
